//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCWebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MST_Manager
    {
        public string ASP_ID { get; set; }
        public int ManageUserId { get; set; }
    }
}
